FROM ubuntu:22.04 AS build

LABEL authors="Oliver Schon, Ernesto Casablanca"
LABEL workspace="lucid"

# Initial setup
RUN apt-get update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y --no-install-recommends curl software-properties-common gpg-agent && \
    apt-get autoremove -y && \
    apt-get clean -y

# Install bazel
ARG BAZELISK_VERSION=v1.26.0
ARG BAZELISK_DOWNLOAD_SHA=6539c12842ad76966f3d493e8f80d67caa84ec4a000e220d5459833c967c12bc
RUN curl -fSsL -o /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-linux-amd64 \
    && ([ "${BAZELISK_DOWNLOAD_SHA}" = "dev-mode" ] || echo "${BAZELISK_DOWNLOAD_SHA} /usr/local/bin/bazel" | sha256sum --check --status - ) \
    && chmod 0755 /usr/local/bin/bazel

# Install required packages
ARG APT_PACKAGES="git build-essential libnlopt-cxx-dev"
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y --no-install-recommends ${APT_PACKAGES} && \
    apt-get autoremove -y && \
    apt-get clean -y

WORKDIR /app
COPY . .

RUN bazel build --config=opt --enable_static_build=True --enable_gurobi_build=False //lucid

ENTRYPOINT [ "pylucid" ]


FROM alpine:3.23.0

LABEL authors="Oliver Schon, Ernesto Casablanca"
LABEL workspace="lucid"

WORKDIR /app

COPY --from=build /app/bazel-bin/lucid /sbin

ENTRYPOINT ["lucid"]
