name: 'Setup Bazel Cache'
description: 'Set up Bazel cache with proper cache keys'

runs:
  using: 'composite'
  steps:
    - name: Cache Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
        repository-cache: true
        external-cache: true
