name: 'Setup Bazel Cache'
description: 'Set up Bazel cache with proper cache keys'

runs:
  using: 'composite'
  steps:
    - name: Cache Bazel
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/bazel
          /private/var/tmp/_bazel_*
          ~/_bazel_*
        key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
        restore-keys: |
          ${{ runner.os }}-bazel-
