name: "Install the Gurobi library"
description: "Make the Gurobi library available for use in the workflow. Note that no licence is provide, so this action won't be able to actually run the Gurobi solver."

inputs:
  os:
    description: "Operating system"
    required: false
    default: "ubuntu"
  arch:
    description: "Architecture to install"
    required: false
    default: "x86_64"
  version:
    description: "Gurobi version to install"
    required: false
    default: "12.0.0"
outputs:
  gurobi-home:
    description: "Gurobi home directory"
    value: ${{ steps.set-gurobi-home.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Download Gurobi
      uses: ethanjli/cached-download-action@v0.1.3
      if: ${{ (startsWith(inputs.os, 'ubuntu')) && (inputs.arch == 'x86_64') }}
      with:
        url: https://packages.gurobi.com/12.0/gurobi${{ inputs.version }}_linux64.tar.gz
        destination: gurobi/gurobi.tar.gz
    - name: Download Gurobi
      uses: ethanjli/cached-download-action@v0.1.3
      if: ${{ (startsWith(inputs.os, 'ubuntu')) && (inputs.arch == 'aarch64') }}
      with:
        url: https://packages.gurobi.com/12.0/gurobi${{ inputs.version }}_armlinux64.tar.gz
        destination: gurobi/gurobi.tar.gz
    - name: Download Gurobi
      uses: ethanjli/cached-download-action@v0.1.3
      if: ${{ startsWith(inputs.os, 'macos') }}
      with:
        url: https://packages.gurobi.com/12.0/gurobi${{ inputs.version }}_macos_universal2.pkg
        destination: gurobi/gurobi.pkg
    - name: Download Gurobi
      uses: ethanjli/cached-download-action@v0.1.3
      if: ${{ startsWith(inputs.os, 'windows') }}
      with:
        url: https://packages.gurobi.com/12.0/Gurobi-${{ inputs.version }}-win64.msi
        destination: gurobi/gurobi.msi

    - name: Extract Gurobi
      if: ${{ startsWith(inputs.os, 'ubuntu') }}
      shell: bash
      run: |
        sudo mkdir -p /opt/gurobi1200/linux64
        sudo tar -xzf ${{ github.workspace }}/gurobi/gurobi.tar.gz -C /opt/gurobi1200/linux64 --strip-components=2
        rm ${{ github.workspace }}/gurobi/gurobi.tar.gz
    - name: Download and extract Gurobi
      if: ${{ startsWith(inputs.os, 'macos') }}
      shell: bash
      run: |
        sudo installer -pkg ${{ github.workspace }}/gurobi/gurobi.pkg -target /
        rm -r ${{ github.workspace }}/gurobi
    - name: Download and extract Gurobi
      if: ${{ startsWith(inputs.os, 'windows') }}
      shell: powershell
      run: |
        choco install lessmsi
        lessmsi x gurobi\gurobi.msi gurobi
        mv ${{ github.workspace }}\gurobi\SourceDir\gurobi1200\win64\* ${{ github.workspace }}\gurobi
        rm ${{ github.workspace }}\gurobi\gurobi.msi

    - name: Set Gurobi home output
      id: set-gurobi-home
      shell: bash
      run: |
        if [[ "${{ inputs.os }}" == macos* ]]; then
          echo "path=/Library/gurobi1200/macos_universal2" >> $GITHUB_OUTPUT
        elif [[ "${{ inputs.os }}" == ubuntu* ]]; then
          echo "path=/opt/gurobi1200/linux64" >> $GITHUB_OUTPUT
        else
          echo "path=${{ github.workspace }}/gurobi" >> $GITHUB_OUTPUT
        fi
